import BufferLayout from "buffer-layout";
import { PublicKey } from "@solana/web3.js";
import { BN } from "@project-serum/anchor";

import { Stream, DecodedStream } from "./types";

const LE = "le"; //little endian
var decoder = new TextDecoder("utf-8");

const TokenStreamDataLayout = BufferLayout.struct<any>([
  BufferLayout.blob(8, "magic"),
  BufferLayout.blob(1, "version"),
  BufferLayout.blob(8, "created_at"),
  BufferLayout.blob(8, "withdrawn_amount"),
  BufferLayout.blob(8, "canceled_at"),
  BufferLayout.blob(8, "end_time"),
  BufferLayout.blob(8, "last_withdrawn_at"),
  BufferLayout.blob(32, "sender"),
  BufferLayout.blob(32, "sender_tokens"),
  BufferLayout.blob(32, "recipient"),
  BufferLayout.blob(32, "recipient_tokens"),
  BufferLayout.blob(32, "mint"),
  BufferLayout.blob(32, "escrow_tokens"),
  BufferLayout.blob(32, "streamflow_treasury"),
  BufferLayout.blob(32, "streamflow_treasury_tokens"),
  BufferLayout.blob(8, "streamflow_fee_total"),
  BufferLayout.blob(8, "streamflow_fee_withdrawn"),
  BufferLayout.blob(4, "streamflow_fee_percent"),
  BufferLayout.blob(32, "partner"),
  BufferLayout.blob(32, "partner_tokens"),
  BufferLayout.blob(8, "partner_fee_total"),
  BufferLayout.blob(8, "partner_fee_withdrawn"),
  BufferLayout.blob(4, "partner_fee_percent"),
  BufferLayout.blob(8, "start_time"),
  BufferLayout.blob(8, "net_deposited_amount"),
  BufferLayout.blob(8, "period"),
  BufferLayout.blob(8, "amount_per_period"),
  BufferLayout.blob(8, "cliff"),
  BufferLayout.blob(8, "cliff_amount"),
  BufferLayout.u8("cancelable_by_sender"),
  BufferLayout.u8("cancelable_by_recipient"),
  BufferLayout.u8("automatic_withdrawal"),
  BufferLayout.u8("transferable_by_sender"),
  BufferLayout.u8("transferable_by_recipient"),
  BufferLayout.u8("can_topup"),
  BufferLayout.blob(64, "stream_name"),
  BufferLayout.blob(8, "withdraw_frequency"),
]);

export const decodeStream = (buf: Buffer): DecodedStream => {
  let raw = TokenStreamDataLayout.decode(buf);

  return {
    magic: new BN(raw.magic, LE),
    version: new BN(raw.version, LE),
    createdAt: new BN(raw.created_at, LE),
    withdrawnAmount: new BN(raw.withdrawn_amount, LE),
    canceledAt: new BN(raw.canceled_at, LE),
    end: new BN(raw.end_time, LE),
    lastWithdrawnAt: new BN(raw.last_withdrawn_at, LE),
    sender: new PublicKey(raw.sender),
    senderTokens: new PublicKey(raw.sender_tokens),
    recipient: new PublicKey(raw.recipient),
    recipientTokens: new PublicKey(raw.recipient_tokens),
    mint: new PublicKey(raw.mint),
    escrowTokens: new PublicKey(raw.escrow_tokens),
    streamflowTreasury: new PublicKey(raw.streamflow_treasury),
    streamflowTreasuryTokens: new PublicKey(raw.streamflow_treasury_tokens),
    streamflowFeeTotal: new BN(raw.streamflow_fee_total, LE),
    streamflowFeeWithdrawn: new BN(raw.streamflow_fee_withdrawn, LE),
    streamflowFeePercent: new BN(raw.streamflow_fee_percent, LE),
    partnerFeeTotal: new BN(raw.partner_fee_total, LE),
    partnerFeeWithdrawn: new BN(raw.partner_fee_withdrawn, LE),
    partnerFeePercent: new BN(raw.partner_fee_percent, LE),
    partner: new PublicKey(raw.partner),
    partnerTokens: new PublicKey(raw.partner_tokens),
    start: new BN(raw.start_time, LE),
    depositedAmount: new BN(raw.net_deposited_amount, LE),
    period: new BN(raw.period, LE),
    amountPerPeriod: new BN(raw.amount_per_period, LE),
    cliff: new BN(raw.cliff, LE),
    cliffAmount: new BN(raw.cliff_amount, LE),
    cancelableBySender: Boolean(raw.cancelable_by_sender),
    cancelableByRecipient: Boolean(raw.cancelable_by_recipient),
    automaticWithdrawal: Boolean(raw.automatic_withdrawal),
    transferableBySender: Boolean(raw.transferable_by_sender),
    transferableByRecipient: Boolean(raw.transferable_by_recipient),
    canTopup: Boolean(raw.can_topup),
    name: decoder.decode(raw.stream_name),
    withdrawFrequency: new BN(raw.withdraw_frequency, LE),
  };
};

export const formatDecodedStream = (stream: DecodedStream): Stream => ({
  magic: stream.magic.toNumber(),
  version: stream.version.toNumber(),
  createdAt: stream.createdAt.toNumber(),
  withdrawnAmount: stream.withdrawnAmount.toNumber(),
  canceledAt: stream.canceledAt.toNumber(),
  end: stream.end.toNumber(),
  lastWithdrawnAt: stream.lastWithdrawnAt.toNumber(),
  sender: stream.sender.toBase58(),
  senderTokens: stream.senderTokens.toBase58(),
  recipient: stream.recipient.toBase58(),
  recipientTokens: stream.recipientTokens.toBase58(),
  mint: stream.mint.toBase58(),
  escrowTokens: stream.escrowTokens.toBase58(),
  streamflowTreasury: stream.streamflowTreasury.toBase58(),
  streamflowTreasuryTokens: stream.streamflowTreasuryTokens.toBase58(),
  streamflowFeeTotal: stream.streamflowFeeTotal.toNumber(),
  streamflowFeeWithdrawn: stream.streamflowFeeWithdrawn.toNumber(),
  streamflowFeePercent: stream.streamflowFeePercent.toNumber(),
  partnerFeeTotal: stream.partnerFeeTotal.toNumber(),
  partnerFeeWithdrawn: stream.partnerFeeWithdrawn.toNumber(),
  partnerFeePercent: stream.partnerFeePercent.toNumber(),
  partner: stream.partner.toBase58(),
  partnerTokens: stream.partnerTokens?.toBase58(),
  start: stream.start.toNumber(),
  depositedAmount: stream.depositedAmount.toNumber(),
  period: stream.period.toNumber(),
  amountPerPeriod: stream.amountPerPeriod.toNumber(),
  cliff: stream.cliff.toNumber(),
  cliffAmount: stream.cliffAmount.toNumber(),
  cancelableBySender: stream.cancelableBySender,
  cancelableByRecipient: stream.cancelableByRecipient,
  automaticWithdrawal: stream.automaticWithdrawal,
  transferableBySender: stream.transferableBySender,
  transferableByRecipient: stream.transferableByRecipient,
  canTopup: stream.canTopup,
  name: stream.name,
  withdrawFrequency: stream.withdrawFrequency.toNumber(),
});
